name: Shared Publish

on:
  workflow_call:
    inputs:
      CWD:
        type: string
        required: true
    secrets:
      NPM_AUTH_TOKEN:
        description: NPM auth token for publishing to NPM
        required: true

jobs:
  check-diff:
    name: Check diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      result: ${{ steps.check-diff.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compare diff changes
        id: check-diff
        run: |
          result=$(git log --oneline --name-only --pretty=format: ${{ github.event.before }}..${{ github.event.after }} | sort -u | grep '${{ inputs.CWD }}' || true)

          if [ -n "$result" ]; then
            echo "result=true" >> "$GITHUB_OUTPUT"
            echo "Following files have changed in ${{ inputs.CWD }}:"
            echo "$result"
          else
            echo "result=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected in ${{ inputs.CWD }}"
          fi

  verify-pkg:
    name: Verify package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-name: ${{ steps.get-artifact-name.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Cache deps
        id: cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ inputs.CWD }}-${{ hashFiles('./yarn.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ inputs.CWD }}
        run: yarn workspaces focus
      - name: Verify package
        working-directory: ${{ inputs.CWD }}
        run: yarn verify
      - name: Define artifact name
        id: get-artifact-name
        run: |
          dirpath=${{ inputs.CWD }};
          name="package-${dirpath//[^[:alnum:]]/_}"
          echo "artifact-name=$name" >> "$GITHUB_OUTPUT"
      - name: Upload artifact for publish jobs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-artifact-name.outputs.artifact-name }}
          path: ${{ inputs.CWD }}

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    needs: [verify-pkg, check-diff]
    if: ${{ needs.check-diff.outputs.result == 'true' }}
    environment: PROD
    permissions:
      contents: read
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Cache deps
        id: cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ inputs.CWD }}-${{ hashFiles('./yarn.lock') }}
          fail-on-cache-miss: true
      - name: Setup NPM TOKEN
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - name: Download artifact to publish
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.verify-pkg.outputs.artifact-name }}
          path: ${{ inputs.CWD }}
      - name: Publish to NPM
        working-directory: ${{ inputs.CWD }}
        run: npm publish

  publish-jsr:
    name: Publish on JSR
    runs-on: ubuntu-latest
    needs: [verify-pkg, check-diff]
    if: ${{ needs.check-diff.outputs.result == 'true' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Cache deps
        id: cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ inputs.CWD }}-${{ hashFiles('./yarn.lock') }}
          fail-on-cache-miss: true
      - name: Download artifact to publish
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.verify-pkg.outputs.artifact-name }}
          path: ${{ inputs.CWD }}
      - name: Publish to JSR
        working-directory: ${{ inputs.CWD }}
        run: npx -y jsr publish
