name: Publish
on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/**
      - packages/azure-feature-flags/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-aff
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package
    strategy:
      matrix:
        package:
          - "packages/azure-feature-flags"

    uses: "./.github/workflows/_shared-publish.yml"
    secrets: inherit
    with:
      CWD: ${{ matrix.package }}
