name: Publish
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    strategy:
      fail-fast: false
      matrix:
        package:
          - "packages/azure-feature-flags"
          - "packages/azure-durable-functions"
          - "packages/azure-functions-vite-plugin"

    uses: "./.github/workflows/_shared-publish.yml"
    secrets: inherit
    with:
      CWD: ${{ matrix.package }}
