name: Publish
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Cache deps
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('./yarn.lock') }}
          path: "node_modules"
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  publish:
    name: Publish
    strategy:
      fail-fast: false
      matrix:
        package:
          - "packages/feature-flags"
          - "packages/durable-functions"
          - "packages/functions-vite-plugin"

    uses: "./.github/workflows/_shared-publish.yml"
    secrets: inherit
    with:
      CWD: ${{ matrix.package }}
