name: Deploy Storybooks Manager functions app

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/storybooks-manager.yml
      - apps/storybooks-manager/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    environment:
      name: "Production"
      url: ${{ steps.deploy.outputs.app-url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            apps/storybooks-manager
          sparse-checkout-cone-mode: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22

        # Move the subdirectory contents to the repository root
      - name: Move subdirectory contents to root
        run: |
          shopt -s dotglob
          mv apps/storybooks-manager/* .
          rm -rf apps

      - name: Install dependencies
        run: |
          npm install
          ls -a .

      - name: "Deploy to Azure Functions"
        id: deploy
        uses: azure/functions-action@v1
        with:
          app-name: "storybooks-manager"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BA1F912C7A4D4E1EB5A2C63EE65421CC }}
          sku: "consumption"
